### ISSUE TITLE
Integrate OnVif

### ISSUE THREAD

**Issue by cgarn3** [cgarn3/GTPD_VMS_Bot#14]
## Story/Task Details
- [ ] Integrate OnVif with Flask
- [ ] Add connection-to-camera test using OnVif
- [ ] Ensure OnVif installs correctly to any platform

## Acceptance Scenarios
1)  Given: A user has access to the backend
    When: The user imports and makes calls to OnVif
    Then: The call should be successful

## Done Done Criteria
Code is merged with master branch, unit tests coded and passing, and PEP8 checkstyle is followed.

**Comment by BenBohannon** [comment]
The onvif python library will require some extra work to integrate. It installs a folder to the incorrect location, and its connections are blocking until a response is received (possible infinite blocking).

Also, onvif doesn't seem to work for the Pelco test camera, but does work for the Avigalon camera.

**Comment by BenBohannon** [comment]
Due to time constraints, we're dropping this feature.
