### ISSUE TITLE
Establish connection with test camera

### ISSUE THREAD

**Issue by cgarn3** [cgarn3/GTPD_VMS_Bot#15]
## Story/Task Details
After a user can successfully leverage OnVif, use OnVif to establish a connection to the test camera.
- [ ] Use OnVif to establish a connection to the test camera
- [x] Test OnVif capabilities with camera

## Acceptance Scenarios
1)  Given: A user with access to OnVif
    When: The user attempts to connect to the test camera
    Then: The connection is successful

## Done Done Criteria
Code is merged with master branch, unit tests coded and passing, and PEP8 checkstyle is followed.

**Comment by BenBohannon** [comment]
Closing Duplicate
