### ISSUE TITLE
Run a simple camera diagnostic

### ISSUE THREAD

**Issue by cgarn3** [cgarn3/GTPD_VMS_Bot#16]
## Story/Task Details
- [ ] Connect to the test camera
- [ ] Utilize OnVif to gather basic diagnostic statistics about the camera (camera name and status to start with)
- [ ] Save diagnostic information to the database

## Acceptance Scenarios
1)  Given: A user with access to app
    When: The user runs a diagnostic on the test camera
    Then: The app should show it was successful and the data should be saved in the database

## Done Done Criteria
Code is merged with master branch, unit tests coded and passing, and PEP8 checkstyle is followed.

**Comment by BenBohannon** [comment]
Closing Duplicate
