### ISSUE TITLE
Import and parse camera IP address excel file

### ISSUE THREAD

**Issue by cgarn3** [cgarn3/GTPD_VMS_Bot#21]
## Story/Task Details
- [ ] import excel file into app
- [ ] parse excel file for camera IP addresses
- [ ] store parsed IP addresses into database

## Acceptance Scenarios
1)  Given: A user with an excel file of camera IP addresses
    When: The user uploads the excel file to the app
    Then: The parsed data should be saved to the database and the user should receive confirmation that it was done

## Done Done Criteria
Code is merged with master branch, unit tests coded and passing, and PEP8 checkstyle is followed.

**Comment by BenBohannon** [comment]
Closing duplicate.
